### ISSUE TITLE
Video Manager

### ISSUE THREAD

**Issue by originell** [TEDxVienna/2014-mainsite-wptheme#1]
We need some way to manage our Videos (youtube playlists/…)

My first dig yielded:

* http://tubepress.com/
* https://wordpress.org/plugins/video-list-manager/
* https://wordpress.org/plugins/contus-video-gallery/

Currently I installed Contus. Let's see how this works out. I think we might need the PRO version.

**Comment by zietho** [comment]
1) tube press (dev.tedxvienna.at/tubepress) is quite simple, but it does not offer categories. It supports Vimeo, but we only need youtube, don't we? It has a few options to control the player, but not really some that makes it stand out if you compare it to CONTUS.
2) wasn't able to install the list manager!
3) Contus, the one you proposed, looks quite straightforward. It supports youtube, dailymotion and offers categories. So, pretty much like what we want. However, I figured it to be quite dull. 

But what I asked myself before trying - what do we need, thus, what are our requirements? 
- youtube support
- able to group videos into categories
- a player that plays the contents
- what else ?

**Comment by IchFloque** [comment]
yup exactly the points you listed.
optionally self made descriptions for each video and or category.

**Comment by IchFloque** [comment]
i thin we are going to stick with the installed plugin, Video Manager and buy the Pro version (99$).
i think it’s really the better solution?

**Comment by zietho** [comment]
I wasn't able to find any better :/..... Other option is to program our own :/. I also don't really like this one that much but it's still the best

**Comment by IchFloque** [comment]
i think it’s quite okay - we go for it
