### ISSUE TITLE
Social Toolbar

### ISSUE THREAD

**Issue by originell** [TEDxVienna/2014-mainsite-wptheme#4]
Social Sharing should be possible on most articles. Lukasz already found something I think?

**Comment by zietho** [comment]
do you mean social sharing, as in facebook, google+ button, etc. or do you mean that posts are automatically posted on the respective social media channels?

**Comment by IchFloque** [comment]
the first thing.
would be even nicer: if we had the tool where you can select any part of the text and share it directly, was a suggestion from the blogger team. a pretty famous blog has it too, forgot which one :)

**Comment by originell** [comment]
[Medium has that](https://medium.com/@erikdkennedy/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda). Select a text and dwell on the amazing toolbar magically appearing.

**Comment by IchFloque** [comment]
what magic luis said.

**Comment by zietho** [comment]
yes but it only share the whole story as far as I've seen and not just the selected text, or am I doing something wrong!? So just to make sure we need: 

1) a plugin that let's the user share the blog post (fb, g+, tw) 
2) a plugin for the post author which automatically shares the new blog post to our social media channels. 
3) we wann have luis magic medium thingies!

**Comment by originell** [comment]
https://wordpress.org/plugins/selection-sharer/

**Comment by IchFloque** [comment]
no, we don’t need nr 2), social media wants to do that manually

**Comment by zietho** [comment]
@originell point 1 is checked by installing the proposed plugin. I did that now, works like a charm. 
![screen shot 2015-02-14 at 19 53 05](https://cloud.githubusercontent.com/assets/4405106/6200677/46fd435a-b483-11e4-98bf-b570a3b961a7.png)

I will also research a few proper tools for sharing the post automatically now.

**Comment by zietho** [comment]
Ok, regarding point 2 I found https://wordpress.org/plugins/social-networks-auto-poster-facebook-twitter-g/

**Comment by IchFloque** [comment]
we no need auto-posts ;)

**Comment by zietho** [comment]
big sry, I did misread your comment, totally waste of my time.. i feel stupid :( !
Sorry for bothering you!

**Comment by IchFloque** [comment]
@zietho: do you know why the facebook share is not showing like in the plugin screenshots? it's in the source code... weird.

**Comment by zietho** [comment]
nope, but also wondered. I can check it

**Comment by IchFloque** [comment]
already solved
