### ISSUE TITLE
Sticky

### ISSUE THREAD

**Issue by originell** [TEDxVienna/2014-mainsite-wptheme#5]
We need to pin/stick posts so they stay in a specific section on the home website. Lukasz is already looking for this. So far it's not very successful

**Comment by IchFloque** [comment]
https://wordpress.org/plugins/nelio-featured-posts/
should do the trick i think

**Comment by IchFloque** [comment]
@zietho

**Comment by IchFloque** [comment]
@LukaszCaputa

**Comment by IchFloque** [comment]
our theme has "featured pages" we might just juse this! 
- taking it above the slider
- adapting the style to make it smaller
- if not possible to select a post instead of a page -> make 3 pages that are links (there is a plugin for that and make sure not open taget=_self

**Comment by IchFloque** [comment]
OR we upgrade to the pro version of our current theme that has an optimized function of this included: http://themesandco.com/extension/customizr-pro/
let me know what you think is best ;)

**Comment by originell** [comment]
Regarding the popularity of the theme and with the future in mind it might be worth the money. Guess they will always update it to the latest WP version, so we shouldn't get stuck in the next couple of years.

**Comment by zietho** [comment]
I agree with Luis! Upgrading sounds like a long term solution, whereas we do not have to take care of two different things!
