### ISSUE TITLE
Team Gallery

### ISSUE THREAD

**Issue by originell** [TEDxVienna/2014-mainsite-wptheme#6]
Find a plugin that makes it possible to create a Team page with each member having a name, various interests and links.

**Comment by IchFloque** [comment]
approved by Lukasz and me:
http://codecanyon.net/item/userpro-user-profiles-with-social-login/full_screen_preview/5958681
costs 28$

**Comment by LukaszCaputa** [comment]
We need some guidelines for team gallery - which fields are necessary, which fields are optional, what is a picture size /constrain. 

It would be great if we could get some sample data to test out the plugin

**Comment by IchFloque** [comment]
Design: https://www.dropbox.com/sh/2cm75ezqe8lheoj/AABi_Beue449kci3RPvce2Cta?dl=0
Facebook member app: https://www.facebook.com/tedxvienna/app_1487243104870564
