### ISSUE TITLE
Research: Make content element .div width of <html> (browser)

### ISSUE THREAD

**Issue by IchFloque** [TEDxVienna/2014-mainsite-wptheme#8]
Please research on who to do this. @zietho @LukaszCaputa 
We need it to make the Slider and Videoplayer-background-canvas full browser width.
Here is an example, but it didn't work on the first try, I don't have more time right now:
http://jsfiddle.net/ygXy6/18/

Please try to make it work for class="videoplayer" and id="customizr-slider".
You can use your browser's "inspect element" function to try things out.
See mockups for reference.

Also: the Slider should look much more like the mockup (previous/nex slide on ledt/right), maybe we can do this somehow??

**Comment by IchFloque** [comment]
maybe @originell can help there as well :)

**Comment by originell** [comment]
oh pretty sophisticated idea with using border-box. Sadly I'm not sure how that works out cross-browser (as [caniuse](http://caniuse.com/#feat=css3-boxsizing) indicates there are some bugs). 

I will ask a friend if she has an idea…

**Comment by originell** [comment]
ok no, she said to either take that element out of the wrapper (can we do that easily?) or simply use JS, as the slider won't work without JS anyways.

**Comment by IchFloque** [comment]
if it's completely out of the wrapper - how would it be positioned correctly (and also be responsive)?

**Comment by originell** [comment]
well basically like a wrapper.. so for full width: `width: 100%` and I guess some nice margin for some spacing :)

**Comment by IchFloque** [comment]
i meant vertical space, so it's on the right position and looks like it's inside the wrapper. also inside the wrappe there needs to be white space for it?

**Comment by IchFloque** [comment]
done by @originell <3 ;)
